name: colasplat
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.8
  - attr=2.5.1
  - blas=1.0
  - boost-cpp=1.78.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - ceres-solver=2.1.0
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - colmap=3.8
  - comm=0.2.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.8
  - dbus=1.13.6
  - debugpy=1.8.14
  - eigen=3.4.0
  - expat=2.7.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.17.0
  - flann=1.9.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeimage=3.18.0
  - freetype=2.13.3
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glew=2.1.0
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.6.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.41
  - harfbuzz=6.0.0
  - hdf5=1.14.2
  - icu=70.1
  - idna=3.7
  - imath=3.1.6
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - jack=1.9.22
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jxrlib=1.1
  - keyutils=1.6.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.1.3
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.13.1.3
  - libcups=2.3.3
  - libcurand=10.3.9.90
  - libcurl=8.12.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdb=6.2.32
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.7.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgcrypt-devel=1.11.0
  - libgcrypt-lib=1.11.0
  - libgcrypt-tools=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.80.2
  - libglu=9.0.0
  - libgomp=14.2.0
  - libgpg-error=1.55
  - libiconv=1.18
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libltdl=2.4.3a
  - libnghttp2=1.58.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libogg=1.3.5
  - libopus=1.5.2
  - libpng=1.6.39
  - libpq=15.3
  - libraw=0.21.1
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libtool=2.5.4
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - metis=5.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.2.1
  - nspr=4.36
  - nss=3.100
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openexr=3.1.5
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.8
  - pcre2=10.43
  - pillow=9.4.0
  - pip=25.0
  - pixman=0.44.2
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pysocks=1.7.1
  - python=3.9.21
  - python_abi=3.9
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - sqlite=3.45.3
  - suitesparse=5.10.1
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.5.1
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - vlfeat=0.9.21
  - wheel=0.45.1
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.2.2
      - addict==2.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bitarray==3.4.2
      - bleach==6.2.0
      - blinker==1.9.0
      - cffi==1.17.1
      - click==8.1.8
      - configargparse==1.7.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - flask==3.1.1
      - fonttools==4.57.0
      - fqdn==1.5.1
      - fsspec==2025.3.2
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.71.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.2.36
      - jedi==0.19.2
      - joblib==1.5.0
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lark==1.2.2
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - lpips==0.1.4
      - markdown==3.8
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mediapy==1.2.3
      - mistune==3.1.3
      - narwhals==2.0.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - nvidia-ml-py==12.575.51
      - nvitop==1.5.1
      - omegaconf==2.3.0
      - open-clip-torch==2.32.0
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.7
      - plotly==6.2.0
      - plyfile==1.1
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - protobuf==6.30.2
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytz==2025.2
      - referencing==0.36.2
      - regex==2024.11.6
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.26.0
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==1.0.15
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torch-scatter==2.1.2
      - torchmetrics==1.7.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20250809
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - submodules/segment-anything-langsplat
      - submodules/colasplat-rasterization
      - submodules/simple-knn
